#pragma once

#define MAX_PARTICLES 30000
#define MAX_LINKS 200
#define CAMERA_FOV 45.0f
#define WINDOW_WIDTH 800.0f
#define WINDOW_HEIGHT 800.0f
#define CAMERA_ASPECT_RATIO WINDOW_WIDTH / WINDOW_HEIGHT
#define CAMERA_NEAR 0.1f
#define CAMERA_FAR 100.0f
#define MAX_PARTICLE_RADIUS 0.15f